name: Build and Conan

on:
  push:
    branches: [ "master" ]

env:
  CMAKELISTS_DIR: ${{github.workspace}}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
           
    - name: Create package
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: conan create . --settings=compiler.cppstd=17
               
    - name: Upload dependencies
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan remote add --insecure cano7782 ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} cano7782 ${{ secrets.CONAN_SERVER_USER }}
        conan upload chemfiles -r=cano7782 --force